[window]
dynamic_title = false
padding.x = 12
padding.y = 4

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[cursor]
# style.shape = "Beam"
style.shape = "Underline"
style.blinking = "On"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/binds.toml"
]
